server:
  port: 8764

spring:
  application:
    name: seg

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB


  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/segmentation?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748
  data:
    redis:
      port: 6379
      database: 0
      host: localhost

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:**/mapper/xml/*.xml
